<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <UserSecretsId>a0295000-5e57-491e-a258-52a3b4280622</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise" Version="1.6.1" />
    <PackageReference Include="Blazorise.Bootstrap" Version="1.6.1" />
    <PackageReference Include="Blazorise.DataGrid" Version="1.6.1" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.6.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.6" PrivateAssets="all" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\main.yml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repository\" />
  </ItemGroup>

</Project>
